# Generated by Django 3.2 on 2022-07-31 17:56

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_author_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='core/imgAuthor', variations={}, verbose_name='Image'),
        ),
    ]
